### ISSUE TITLE
Disable/change "No price to set" error

### ISSUE THREAD

**Issue by alyssadev** [SHOEGAZEssb/Dagobert#3]
![image](https://github.com/user-attachments/assets/f034481b-9c7d-4951-87c0-38f981e36780)

(I'm not sure, looking at the code, why the extra text is printed before the item name)

I'd like the option to disable this message please, the previous behaviour of leaving the price as-is would be fine. IMO the error is unnecessary when it's printed to xllog anyway but it's not my project and I'm grateful for your work.

https://github.com/SHOEGAZEssb/Dagobert/blob/master/Dagobert/AutoPinch.cs#L293

**Comment by SHOEGAZEssb** [comment]
I'm gonna add an option to disable it.
Leaving as is should usually be fine but my personal usecase is dumping items into my retainer sell list and using AutoPinch to set the prices. Without the warning I would have items as their shop selling price without knowing.
